### PR TITLE
locking in pandas dependency

### PR DESCRIPTION
**Pull request by mortonjt**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mortonjt** [comment]
@fedarko fyi we are going to restrict pandas in light of this [issue](https://github.com/biocore/songbird/issues/128). If you see any qualms with this, feel free to let me know.

**Comment by fedarko** [comment]
Sounds good to me, thanks!

**Comment by fedarko** [comment]
shoot, just noticed something that may cause problems -- since the version wasn't changed we may need to update the build number to `1` in order to indicate that this is a new build and everything.

Not sure if this will mess things up, but if https://anaconda.org/conda-forge/songbird doesn't update within some time it may be worth another PR that bumps up the build number. sorry for not catching earlier

**Comment by mortonjt** [comment]
good catch (forgot about that too)

**Pull request merged**
